# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec file for Phoenix Command."""

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'phoenix_command',
        'phoenix_command.gui',
        'phoenix_command.gui.dialogs',
        'phoenix_command.gui.dialogs.shot_dialog',
        'phoenix_command.gui.dialogs.burst_fire_dialog',
        'phoenix_command.gui.dialogs.shotgun_dialog',
        'phoenix_command.gui.dialogs.shotgun_burst_fire_dialog',
        'phoenix_command.gui.dialogs.three_round_burst_dialog',
        'phoenix_command.gui.dialogs.character_dialog',
        'phoenix_command.gui.dialogs.equipment_dialog',
        'phoenix_command.gui.dialogs.explosion_damage_dialog',
        'phoenix_command.gui.dialogs.explosive_weapon_dialog',
        'phoenix_command.gui.dialogs.auto_grenade_launcher_dialog',
        'phoenix_command.gui.dialogs.thrown_grenade_dialog',
        'phoenix_command.gui.widgets',
        'phoenix_command.gui.widgets.character_card',
        'phoenix_command.gui.widgets.character_list',
        'phoenix_command.gui.widgets.combat_log',
        'phoenix_command.gui.widgets.combat_zone',
        'phoenix_command.gui.widgets.stats_display',
        'phoenix_command.gui.character_manager',
        'phoenix_command.gui.main_window',
        'phoenix_command.models',
        'phoenix_command.models.character',
        'phoenix_command.models.enums',
        'phoenix_command.models.gear',
        'phoenix_command.models.hit_result_advanced',
        'phoenix_command.models.hit_result_simple',
        'phoenix_command.models.recovery',
        'phoenix_command.simulations',
        'phoenix_command.simulations.combat_simulator',
        'phoenix_command.simulations.combat_simulator_probabilities',
        'phoenix_command.simulations.combat_simulator_utils',
        'phoenix_command.simulations.character_generator',
        'phoenix_command.item_database',
        'phoenix_command.item_database.armor',
        'phoenix_command.item_database.character_templates',
        'phoenix_command.item_database.equipment',
        'phoenix_command.item_database.grenades',
        'phoenix_command.item_database.weapons',
        'phoenix_command.tables',
        'phoenix_command.tables.core',
        'phoenix_command.tables.core.table1_character_generation',
        'phoenix_command.tables.core.table2_odds_of_hitting',
        'phoenix_command.tables.core.table3_hit_location_and_damage',
        'phoenix_command.tables.core.table4_advanced_odds_of_hitting',
        'phoenix_command.tables.core.table5_auto_pellet_shrapnel',
        'phoenix_command.tables.core.table8_healing_and_recovery',
        'phoenix_command.tables.advanced_rules',
        'phoenix_command.tables.advanced_rules.blunt_damage',
        'phoenix_command.tables.advanced_rules.effective_min_arc',
        'phoenix_command.tables.advanced_rules.three_round_burst',
        'phoenix_command.tables.advanced_damage_tables',
        'phoenix_command.tables.advanced_damage_tables.advanced_damage_calculator',
        'phoenix_command.tables.advanced_damage_tables.tables_data',
        'phoenix_command.tables.advanced_damage_tables.table_1_get_hit_location',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pytest',
        'tests',
        '_pytest',
        'pluggy',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, cipher=block_cipher)

# Single-file EXE (onefile mode)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PhoenixCommand',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,        # GUI-приложение, без консольного окна
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
