from enum import Enum


class ShooterStance(Enum):
    STANDING = 0
    KNEELING = 3
    PRONE = 6
    HIP_FIRING = -6

class TargetExposure(Enum):  # Renamed from TargetSize to reflect exposure/situation
    LOOKING_OVER_COVER = -4
    FIRING_OVER_COVER = 0
    STANDING_EXPOSED = 8
    KNEELING_EXPOSED = 6
    PRONE_EXPOSED = 2

class ExplosiveTarget(Enum):
    HEX = 12
    WINDOW = 9
    DOOR = 13

class DamageType(Enum):
    LOW_VELOCITY = "LOW_VELOCITY"
    OVER_PENETRATING = "OVER_PENETRATING"

class WoundType(Enum):
    SUPERFICIAL_WOUND = "SUPERFICIAL_WOUND"
    LIGHT_WOUND = "LIGHT_WOUND"
    MEDIUM_WOUND = "MEDIUM_WOUND"
    HEAVY_WOUND = "HEAVY_WOUND"
    CRITICAL_WOUND = "CRITICAL_WOUND"
    DISABLING_INJURY = "DISABLING_INJURY"
    DEAD = "DEAD"
    WEAPON_CRITICAL = "WEAPON_CRITICAL"

class HitLocation(Enum):
    HEAD_GLANCE = 'HEAD_GLANCE'
    HEAD_FOREHEAD = 'HEAD_FOREHEAD'
    HEAD_EYE_NOSE = 'HEAD_EYE_NOSE'
    HEAD_MOUTH = 'HEAD_MOUTH'
    ARM_GLANCE = 'ARM_GLANCE'
    ARM_SHOULDER = 'ARM_SHOULDER'
    ARM_UPPER_ARM_FLESH = 'ARM_UPPER_ARM_FLESH'
    ARM_UPPER_ARM_BONE = 'ARM_UPPER_ARM_BONE'
    ARM_FOREARM_FLESH = 'ARM_FOREARM_FLESH'
    ARM_FOREARM_BONE = 'ARM_FOREARM_BONE'
    ARM_HAND = 'ARM_HAND'
    ARM_WEAPON = 'ARM_WEAPON'
    BODY_GLANCE = 'BODY_GLANCE'
    BODY_CHEST = 'BODY_CHEST'
    BODY_BASE_OF_NECK = 'BODY_BASE_OF_NECK'
    BODY_HEART = 'BODY_HEART'
    BODY_SPINE = 'BODY_SPINE'
    BODY_ABDOMEN = 'BODY_ABDOMEN'
    BODY_PELVIS = 'BODY_PELVIS'
    LEG_GLANCE = 'LEG_GLANCE'
    LEG_THIGH_FLESH = 'LEG_THIGH_FLESH'
    LEG_THIGH_BONE = 'LEG_THIGH_BONE'
    LEG_SHIN_FOOT = 'LEG_SHIN_FOOT'